wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.15
    start_time: 1672287286.194429
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      - 63
      - 74
      2:
      - 1
      - 41
      - 51
      - 55
      - 63
      - 74
      3:
      - 16
      - 23
      4: 3.9.15
      5: 0.13.7
      8:
      - 2
      - 5
batch_size:
  desc: null
  value: 16
device:
  desc: null
  value: cuda:0
max_iter:
  desc: null
  value: 80000
model:
  desc: null
  value: DeeplabV3+
